# Generated by Django 3.2.5 on 2021-07-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('isin', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=100)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moex.issuer')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moex.security')),
            ],
        ),
    ]
