# Generated by Django 3.2.5 on 2021-07-10 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='moex.security'),
        ),
        migrations.AlterField(
            model_name='security',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='moex.issuer'),
        ),
    ]
