# Generated by Django 3.2.5 on 2021-07-25 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moex', '0003_auto_20210724_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuer',
            name='external_id',
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('security', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='moex.security')),
            ],
        ),
    ]
